#version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=qcPT-3_vxi73dN2n_cKF
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elastic/config.yaml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTowVHNobEljc1RTQ3RLZFhWUHNkbG1R
    volumes:
      - ./kibana/config.yaml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.17.0
    container_name: apm-server
    ports:
      - "8200:8200"
    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_USERNAME=qcPT-3_vxi73dN2n_cKF
#      - kibana.host=http://kibana:5601
#      - logging.level=debug
      - apm-server.rum.enabled=true
#      - setup.kibana.host=kibana:5601
#      - setup.template.settings.index.number_of_replicas=0
#      - apm-server.kibana.enabled=true
#      - apm-server.kibana.host=kibana:5601
#      - output.elasticsearch.username=elastic
#      - output.elasticsearch.password=changeme
    volumes:
      - ./apm/config.yaml:/usr/share/apm-server/apm-server.yml
    depends_on:
      - elasticsearch
      - kibana

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/config.yaml:/etc/otel-collector-config.yaml
    ports:
#      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  # Metrics endpoint
    depends_on:
      - apm-server
    links:
      - socat

  # mac workaround for docker-stats
  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"

  fluent-bit:
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parser_docker.conf:/fluent-bit/etc/parser_docker.conf
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
