version: '3'
services:
  nodejs-logging:
    container_name: nodejs-logging
    build: .
    ports:
      - 3000:3000
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.{{.Name}}